[package]
name = "ui3"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
name = "ui"
path = "src/ui.rs"

[dependencies]
chrono.workspace = true
gpui = { path = "../gpui3", package = "gpui3" }
itertools = { workspace = true, optional = true }
menu.workspace = true
serde.workspace = true
settings.workspace = true
smallvec.workspace = true
story = { workspace = true, optional = true }
strum = { workspace = true, features = ["derive"] }
theme = { path = "../theme3", package = "theme3" }
ui_macros.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[features]
default = []
stories = ["dep:itertools", "dep:story"]
