[package]
name = "theme3"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[features]
default = []
test-support = ["gpui/test-support", "fs/test-support", "settings/test-support"]

[lib]
path = "src/theme.rs"
doctest = false

[dependencies]
anyhow.workspace = true
collections.workspace = true
derive_more.workspace = true
fs = { path = "../fs3", package = "fs3" }
futures.workspace = true
gpui = { path = "../gpui3", package = "gpui3" }
indexmap.workspace = true
log.workspace = true
palette = { workspace = true, default-features = false, features = ["std"] }
parking_lot.workspace = true
refineable.workspace = true
schemars = { workspace = true, features = ["indexmap"] }
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
serde_json_lenient.workspace = true
serde_repr.workspace = true
settings = { path = "../settings3", package = "settings3" }
strum.workspace = true
util.workspace = true
uuid.workspace = true

[dev-dependencies]
fs = { path = "../fs3", package = "fs3", features = ["test-support"] }
gpui = { path = "../gpui3", package = "gpui3", features = ["test-support"] }
settings = { path = "../settings3", package = "settings3", features = ["test-support"] }
