[package]
name = "settings3"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/settings.rs"
doctest = false

[features]
test-support = ["gpui/test-support", "fs/test-support"]

[dependencies]
anyhow.workspace = true
collections.workspace = true
ec4rs.workspace = true
fs = { path = "../fs3", package = "fs3" }
futures.workspace = true
gpui = { path = "../gpui3", package = "gpui3" }
log.workspace = true
paths.workspace = true
release_channel.workspace = true
rust-embed.workspace = true
schemars.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
serde_json_lenient.workspace = true
smallvec.workspace = true
tree-sitter-json.workspace = true
tree-sitter.workspace = true
util.workspace = true

[dev-dependencies]
fs = { path = "../fs3", package = "fs3", features = ["test-support"] }
gpui = { path = "../gpui3", package = "gpui3", features = ["test-support"] }
indoc.workspace = true
pretty_assertions.workspace = true
unindent.workspace = true
