[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/telemetry.rs"

[dependencies]
semantic_version.workspace = true
serde.workspace = true
futures.workspace = true
erased-serde.workspace = true
