[package]
name = "menu3"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/menu.rs"
doctest = false

[dependencies]
gpui = { path = "../gpui3", package = "gpui3" }
serde = { workspace = true }
