[package]
name = "markdown_preview"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/markdown_preview.rs"

[features]
test-support = []

[dependencies]
rand.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
collections.workspace = true
editor.workspace = true
gpui.workspace = true
language.workspace = true
linkify.workspace = true
log.workspace = true
pretty_assertions.workspace = true
pulldown-cmark.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
workspace.workspace = true

[dev-dependencies]
cowstr.workspace = true
editor = { workspace = true, features = ["test-support"] }
proptest.workspace = true
pulldown-cmark-to-cmark.workspace = true
