[package]
name = "zeta"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"
exclude = ["fixtures"]

[lints]
workspace = true

[lib]
path = "src/zeta.rs"
doctest = false

[dependencies]
anyhow.workspace = true
collections.workspace = true
futures.workspace = true
gpui.workspace = true
http_client.workspace = true
inline_completion.workspace = true
language.workspace = true
log.workspace = true
open_ai.workspace = true
similar.workspace = true

[dev-dependencies]
collections = { workspace = true, features = ["test-support"] }
ctor.workspace = true
env_logger.workspace = true
gpui = { workspace = true, features = ["test-support"] }
http_client = { workspace = true, features = ["test-support"] }
indoc.workspace = true
language = { workspace = true, features = ["test-support"] }
reqwest_client = { workspace = true, features = ["test-support"] }
rpc = { workspace = true, features = ["test-support"] }
tree-sitter-go.workspace = true
tree-sitter-rust.workspace = true
worktree = { workspace = true, features = ["test-support"] }
